name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Clean install frontend
        working-directory: ./frontend
        run: rm -rf node_modules package-lock.json && npm install
        
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
      - name: Docker tests
        run: |
          docker compose -f docker-compose.test.yml up --build backend-test --abort-on-container-exit 2>&1
